"""
Django settings for store project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path
from decouple import config, Csv
import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6sha*qzn=0udkb8+q8+29tc$scd^t^yf9m^z#@%m*#o5@_=%9('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG')

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    "https://layersoftruth.org",
    "https://store.layersoftruth.org",
]


AUTH_USER_MODEL = 'user.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user.apps.UserConfig',
    'shelf.apps.ShelfConfig',
    'cart.apps.CartConfig',
    'dashboard.apps.DashboardConfig',

    'rest_framework',
    'crispy_forms',
    'crispy_bootstrap5',
    'fontawesomefree',
    'import_export',
    'paystack',
    'requests',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['temp'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'store.context.Context',
            ],
        },
    },
]

WSGI_APPLICATION = 'store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# Database
if DEBUG == False:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config('MYSQL_NAME'),
            'USER': config('MYSQL_USER'),
            'PASSWORD': config('MYSQL_PASSWORD'),
            'HOST': config('MYSQL_HOST'),
            'PORT': config('MYSQL_PORT'),
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            }
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us' 

USE_I18N = False
 
TIME_ZONE = 'Africa/Lagos'
USE_TZ = True
 
 
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/



# Static & Media Files
if DEBUG == False:
    STATIC_URL = 's/'
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'home/static'),  # Add your existing static directory
        os.path.join(BASE_DIR, 'users/static'),  # Add another static directory
    ]

    STATIC_ROOT = BASE_DIR / "staticfiles"

    MEDIA_URL = 'media/'
    MEDIA_ROOT = BASE_DIR / "media"
else:
    INSTALLED_APPS += ['storages']

    AWS_ACCESS_KEY_ID = config("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = config("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME", "us-east-1")  # default to us-east-1 if not set
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

    AWS_LOCATION_STATIC = "lot-store/static"
    AWS_LOCATION_MEDIA = "lot-store/media"
    AWS_S3_OBJECT_PARAMETERS = {
        "CacheControl": "max-age=86400",
    }
    AWS_STATIC_LOCATION = AWS_LOCATION_STATIC
    AWS_MEDIA_LOCATION = AWS_LOCATION_MEDIA
    STATICFILES_LOCATION = AWS_STATIC_LOCATION
    MEDIAFILES_LOCATION = AWS_MEDIA_LOCATION
    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_STATIC_LOCATION}/"
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_MEDIA_LOCATION}/"

    AWS_QUERYSTRING_AUTH = False  # makes URLs public (optional)

    # ✅ NEW: Tell Django to use S3 backends (this was the missing engine!)
    STORAGES = {
        "default": {
            "BACKEND": "store.storages.MediaStorage"
        },
        "staticfiles": {
            "BACKEND": "store.storages.StaticStorage"
        }
    }

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/account/Login'
LOGOUT_REDIRECT_URL = '/account/Login'
LOGOUT_URL = '/account/Logout'


# Email Config
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT', cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')
SERVER_EMAIL = config('SERVER_EMAIL')

CKEDITOR_UPLOAD_PATH = "/ckeditor/upload/"
CKEDITOR_ALLOW_NONIMAGE_FILES = False

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Full',
        'filebrowserUploadUrl': '/ckeditor/upload/',  # Your URL for image uploads
        'filebrowserImageUploadUrl': '/ckeditor/upload/',  # Image upload URL
    },
}

PAYSTACK_SECRET_KEY = "sk_live_2390fb9dbc3ad32acc505935e2bc62069934d42e"
PAYSTACK_PUBLIC_KEY = "pk_live_7a5e44df04f404d753aee0915134170d4efeddb7"


# PAYSTACK_SECRET_KEY = "sk_test_84874e746f8e69edc6b30d297855a63bd97b1965"
# PAYSTACK_PUBLIC_KEY = "pk_test_21442e7159ef1775f5e93eba495cdf8a040ab6f9"

