# Generated by Django 5.2.13 on 2026-10-02 23:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelf', '0003_product_customizable_product_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('changes_requested', 'Changes requested'), ('resubmitted', 'Resubmitted'), ('quoted', 'Quoted'), ('quote_accepted', 'Quote accepted'), ('quote_declined', 'Quote declined'), ('paid', 'Paid'), ('in_production', 'In production'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=24)),
                ('variant', models.CharField(blank=True, max_length=100)),
                ('size_quantities', models.JSONField(default=dict)),
                ('note', models.TextField(blank=True)),
                ('rights_confirmed', models.BooleanField(default=False)),
                ('current_design', models.JSONField(blank=True, default=dict)),
                ('preview', models.ImageField(blank=True, upload_to='designer/previews/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_requests', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='design_requests', to='shelf.product')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='DesignMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='designer.designrequest')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='DesignAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='designer/assets/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='designer.designrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DesignVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('design_data', models.JSONField()),
                ('preview', models.ImageField(blank=True, upload_to='designer/versions/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='designer.designrequest')),
            ],
            options={
                'ordering': ('-number',),
                'unique_together': {('request', 'number')},
            },
        ),
        migrations.CreateModel(
            name='DesignQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('explanation', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_quote', to='shelf.product')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='designer.designrequest')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='designer.designversion')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMockupView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='designer/mockups/%Y/%m/')),
                ('print_x', models.PositiveIntegerField(default=250)),
                ('print_y', models.PositiveIntegerField(default=180)),
                ('print_width', models.PositiveIntegerField(default=400)),
                ('print_height', models.PositiveIntegerField(default=500)),
                ('output_width', models.PositiveIntegerField(default=1800)),
                ('output_height', models.PositiveIntegerField(default=1800)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mockup_views', to='shelf.product')),
            ],
            options={
                'ordering': ('position', 'id'),
                'unique_together': {('product', 'name')},
            },
        ),
    ]
