# Generated by Django 5.2.17 on 2026-10-02 16:48

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(default=0)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='product/%y/%m/%d/')),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField(verbose_name='number of Available Stock')),
                ('description', models.TextField()),
                ('pay', models.CharField(choices=[('Pay on Delivery', 'Pay on Delivery'), ('Pay before Delivery', 'Pay                                                                  before Delivery')], default='Pay before Delivery', max_length=25)),
                ('delivery', models.CharField(choices=[('Free Delivery', 'Free Delivery'), ('Delivery Fee', 'Delivery Fee')], default='Delivery Fee', max_length=25)),
                ('productType', models.CharField(choices=[('Single Buy', 'Single Buy'), ('Min. Buy', 'Min. Buy'), ('Gift on Buy', 'Gift on Buy')], default='Single Buy', max_length=25)),
                ('minBuy', models.IntegerField(default=1, verbose_name='minBuy')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('categories', models.ManyToManyField(related_name='product', to='shelf.category')),
            ],
        ),
    ]
