# Generated by Django 5.2.13 on 2026-10-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customizable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_public',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
